name: Build Status

on:
  push:
    branches: [ main, master, build-action ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2

    - name: Install node
      uses: actions/setup-node@v3

    - name: Install SASS
      # Using slower node version because it's easier to install in CI
      run: npm install -g sass

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test ./...
